version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/openjdk:stretch
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test

    steps:
      - checkout
      - restore_cache:
          key: circleci-SEPTProjectfromSC-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-SEPTProjectfromSC-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/bookmicroservices-0.0.1.jar