version: 2
jobs:

  build:
    working_directory: ~/src
    docker:
      - image: circleci/openjdk:stretch
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test

    steps:
      - checkout
      - restore_cache:
          key: circleci-SEPTProjectfromSC-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-SEPTProjectfromSC-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_artifacts:
          path: target/reviewmicroservices-0.0.1.jar


  test:
    working_directory: ~/src
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
