version: 2.1
  orbs:
    aws-s3: circleci/aws-s3@x.y.z # use the AWS S3 orb in your config

  jobs: # Define the build and deploy jobs
    build:
      working_directory: ~/src
      docker: # Use the Docker executor for the build job
        - image: circleci/openjdk:stretch # Specify the Docker image to use for the build job
        - image: circleci/postgres:9.6.3-alpine
          environment:
            POSTGRES_USER: root
            POSTGRES_DB: circle-test # context / project UI env-var reference
    ... # build job steps omitted for brevity
    deploy:
      docker: # Use the Docker executor for the deploy job
        - image: <image-name-and-tag>  # Specify the Docker image to use for the deploy job
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - aws-s3/sync:
          from: bucket
          to: 's3://my-s3-bucket-name/prefix'
          arguments: | # Optional arguments
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true # default is false

  workflows: # Define a Workflow running the build job, then the deploy job
    version: 2
    build-deploy: # Make a workflow to build and deploy your project
      jobs:
        - build
        - deploy:
            requires:
              - build # Only run deploy job once the build job has completed
            filters:
              branches:
                only: master # Only deploy when the commit is on the Master branch