version: 2

jobs: # Define the build and deploy jobs
  build:
    working_directory: ~/src
    docker: # Use the Docker executor for the build job
      - image: circleci/openjdk:stretch # Specify the Docker image to use for the build job
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test # context / project UI env-var reference
  ... # build job steps omitted for brevity
  deploy:
    working_directory: ~/src
    docker: # Use the Docker executor for the build job
      - image: circleci/openjdk:stretch # Specify the Docker image to use for the build job
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test # context / project UI env-var reference
    steps:
      - run: # Install the AWS CLI if it is not already included in the docker image
          name: Install awscli
          command: sudo pip install awscli
      - run: # Deploy to S3 using the sync command
          name: Deploy to S3
          command: aws s3 sync <path/to/bucket> <s3://location/in/S3-to-deploy-to>

workflows: # Define a Workflow running the build job, then the deploy job
  version: 2
  build-deploy: # Make a workflow to build and deploy your project
    jobs:
      - build
      - deploy:
          requires:
            - build # Only run deploy job once the build job has completed
          filters:
            branches:
              only: master # Only deploy when the commit is on the Master branch

